#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: #@ data.values.ceph_csi_rbd.namespace
stringData:
  # User ID should have required access to the 'pool' specified in the storage class
  userID: #@ data.values.ceph_csi_rbd.user_id
  userKey: #@ data.values.ceph_csi_rbd.user_key 

  # Encryption passphrase
  # encryptionPassphrase: test_passphrase
